import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    height: '100%',
  },
  personNameDark: {
    color: 'white',
    fontSize: 18,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginTop: 5,
    fontWeight: '500',
  },
  personNameLight: {
    color: 'black',
    fontSize: 18,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginTop: 5,
    fontWeight: '500',
  },
  otherTextDark: {
    color: 'white',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  otherTextLight: {
    color: 'black',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  bottomContainer: {
    backgroundColor: '#1A6295',
    height: 60,
  },
  addButton: {
    marginTop: 5,
    backgroundColor: '#1A6295',
    paddingTop: 10,
    borderColor: 'white',
    borderWidth: 2,
    borderRadius: 10,
    height: 50,
    width: '95%',
    alignSelf: 'center',
  },
  addText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
    justifyContent: 'center',
  },
  complete: {
    width: 200,
    color: 'orange',
    fontSize: 16,
  },
  completeView: {
    backgroundColor: 'green',
    fontSize: 20,
    alignContent: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingLeft: 20,
  },
  postponeView: {
    backgroundColor: 'orange',
    fontSize: 20,
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  postpone: {
    width: 200,
    color: 'white',
    textAlign: 'left',
    marginLeft: 10,
    fontSize: 16,
  },
  rowDark: {
    paddingTop: 10,
    backgroundColor: 'black',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    paddingBottom: 10,
  },
  rowLight: {
    paddingTop: 10,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    paddingBottom: 10,
  },
  rightSwipeItem: {
    justifyContent: 'center',
    margin: 0,
    alignContent: 'center',
    width: 150,
    backgroundColor: '#34ABF7',
  },
  transactionRow: {
    display: 'flex',
    flexDirection: 'row',
    padding: 1,
    justifyContent: 'space-between',
    color: 'black',
  },
  transactionDateDark: {
    color: 'white',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginRight: 10,
  },
  transactionDateLight: {
    color: 'black',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginRight: 10,
  },
});
