import { StyleSheet } from 'react-native';

export const stylesPop = StyleSheet.create({
  rowDark: {
    flexDirection: 'row',
    paddingTop: 10,
    backgroundColor: 'black',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    height: 140,
  },
  rowLight: {
    flexDirection: 'row',
    paddingTop: 10,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    height: 140,
  },
  rankBox: {
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 50,
    width: '15%',
  },
  rankingCircle: {
    height: 30,
    width: 30,
  },
  textBoxDark: {
    flexDirection: 'column',
    height: 80,
    backgroundColor: 'black',
    width: '55%',
    marginLeft: 5,
    textAlign: 'left',
  },
  textBoxLight: {
    flexDirection: 'column',
    height: 80,
    backgroundColor: 'white',
    width: '55%',
    marginLeft: 5,
    textAlign: 'left',
  },
  nameTextDark: {
    color: 'white',
    fontSize: 16,
    textAlign: 'left',
    fontWeight: '500',
  },
  nameTextLight: {
    color: 'black',
    fontSize: 16,
    textAlign: 'left',
    fontWeight: '500',
  },
  distanceTextDark: {
    color: 'white',
    fontSize: 16,
    marginTop: 9,
  },
  distanceTextLight: {
    color: 'black',
    fontSize: 16,
    marginTop: 9,
  },
  phoneText: {
    color: '#1398F5',
    fontSize: 16,
    textAlign: 'left',
    marginBottom: 10,
    marginTop: 15,
  },
  noPhoneText: {
    color: 'gray',
    fontSize: 16,
    textAlign: 'left',
    marginBottom: 10,
    marginTop: 15,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginTop: 7,
  },
  directionsAndCompleteText: {
    color: '#1398F5',
    fontSize: 16,
    textAlign: 'left',
    marginRight: 20,
  },
  saveText: {
    color: '#1398F5',
    fontSize: 16,
    textAlign: 'left',
    marginRight: 20,
  },
  savedText: {
    color: 'gray',
    fontSize: 16,
    textAlign: 'left',
    marginRight: 20,
  },
  removeText: {
    color: 'red',
    fontSize: 16,
    textAlign: 'left',
  },
  chevronBox: {
    flexDirection: 'row',
    paddingTop: 30,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 15,
    width: '30%',
  },
  chevron: {
    height: 20,
    width: 12,
    marginTop: 9,
  },
  buttonText: {
    color: '#1398F5',
    fontSize: 16,
    textAlign: 'left',
    marginRight: 20,
  },
  upAndDownRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    height: 40,
    borderColor: 'gray',
    borderWidth: 0.25,
  },
  chevronView: {
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoView: {
    paddingLeft: 10,
    flexDirection: 'row',
    width: '75%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoTextDark: {
    color: 'white',
    paddingTop: 4,
    fontSize: 16,
  },
  infoTextLight: {
    color: 'black',
    paddingTop: 4,
    fontSize: 16,
  },
  actionAndFilterButtonView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  filterView: {
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingTop: 8,
    width: '50%',
  },
  pinFilterShow: {
    width: 30,
    height: 43,
    opacity: 1.0,
  },
  pinFilterDim: {
    width: 30,
    height: 43,
    opacity: 0.4,
  },
  actionButtonView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '20%',
    paddingTop: 8,
  },
  actionButtons: {
    width: 40,
    height: 40,
  },
  centerButton: {
    width: 40,
    height: 40,
    right: 20,
  },
  upAndDownButtons: {
    width: 25,
    height: 15,
    opacity: 1.0,
  },
  upAndDownButtonsDim: {
    width: 25,
    height: 15,
    opacity: 0.4,
  },
  mapViewShort: {
    height: '0%',
    width: '100%',
  },
  mapViewMedium: {
    height: '50%',
    width: '100%',
  },
  mapViewLong: {
    height: '70%',
    width: '100%',
  },
  map: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  bottomView: {
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
    bottom: 10,
    alignSelf: 'flex-end',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
});
