import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerDark: {
    backgroundColor: 'black',
    height: '100%',
  },
  containerLight: {
    backgroundColor: 'white',
    height: '100%',
  },
  personNameDark: {
    color: 'white',
    fontSize: 18,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginTop: 5,
    fontWeight: '500',
  },
  personNameLight: {
    color: 'black',
    fontSize: 18,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
    marginTop: 5,
    fontWeight: '500',
  },
  phoneNumber: {
    color: '#1398F5',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 5,
  },
  popByButtons: {
    color: '#1398F5',
    fontSize: 15,
    textAlign: 'right',
    marginRight: 10,
    marginBottom: 5,
  },
  saveToMapButton: {
    color: '#1398F5',
    fontSize: 15,
    textAlign: 'right',
    marginRight: 10,
    marginTop: -3,
  },
  savedButton: {
    color: 'gray',
    fontSize: 15,
    textAlign: 'right',
    marginRight: 10,
    marginTop: -3,
  },
  phoneRow: {
    width: 210,
  },
  otherTextDark: {
    color: 'white',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  otherTextLight: {
    color: 'black',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  streetTextDark: {
    color: 'white',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
  },
  streetTextLight: {
    color: 'black',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
  },
  cityStateZipTextDark: {
    color: 'white',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  cityStateZipTextLight: {
    color: 'black',
    fontSize: 15,
    textAlign: 'left',
    marginLeft: 10,
    marginBottom: 7,
  },
  bottomContainer: {
    backgroundColor: '#1A6295',
    height: 60,
  },
  ideasButton: {
    marginTop: 5,
    backgroundColor: '#1A6295',
    paddingTop: 10,
    borderColor: 'white',
    borderWidth: 2,
    borderRadius: 10,
    height: 50,
    width: '95%',
    alignSelf: 'center',
  },
  ideasText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
    justifyContent: 'center',
  },
  complete: {
    width: 200,
    color: 'orange',
    fontSize: 16,
  },
  completeView: {
    backgroundColor: 'green',
    fontSize: 20,
    alignContent: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingLeft: 20,
  },
  postponeView: {
    backgroundColor: 'orange',
    fontSize: 20,
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  postpone: {
    width: 200,
    color: 'white',
    textAlign: 'left',
    marginLeft: 10,
    fontSize: 16,
  },
  row: {
    // delete
    paddingTop: 10,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    paddingBottom: 10,
  },
  rowDark: {
    paddingTop: 10,
    backgroundColor: 'black',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    paddingBottom: 10,
  },
  rowLight: {
    paddingTop: 10,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderWidth: 0.5,
    paddingBottom: 10,
  },
  tabButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 40,
    alignItems: 'center',
  },
  popbyRow: {
    display: 'flex',
    flexDirection: 'row',
    padding: 1,
    justifyContent: 'space-between',
  },
  unselected: {
    color: 'lightgray',
    textAlign: 'center',
    fontSize: 16,
    height: '100%',
    backgroundColor: '#09334a',
    flex: 1,
    paddingTop: 10,
  },
  selected: {
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    height: '100%',
    backgroundColor: '#04121b',
    flex: 1,
    paddingTop: 10,
    borderColor: 'lightblue',
    borderWidth: 2,
  },
  progress: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  notes: {
    width: 200,
    color: '#1A6295',
    textAlign: 'left',
    marginLeft: 10,
    fontSize: 16,
  },
  leftSwipeItem: {
    justifyContent: 'center',
    margin: 0,
    alignContent: 'center',
    width: 100,
    backgroundColor: '#F9741A',
  },
  rightSwipeItem: {
    justifyContent: 'center',
    margin: 0,
    alignContent: 'center',
    width: 100,
    backgroundColor: '#56BE42',
  },
  hackDark: {
    height: 100,
    backgroundColor: 'black',
  },
  hackLight: {
    height: 100,
    backgroundColor: 'white',
  },
  postponeButton: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    color: 'white',
    fontSize: 18,
  },
  postponeButtonTouch: {
    height: '100%',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    color: 'white',
    fontSize: 18,
  },
});
